# Based on
# https://github.com/rust-lang/rustfmt/blob/rustfmt-1.4.19/Configurations.md

# Stable
edition = "2021"
max_width = 80
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Max"
newline_style = "Unix"

# Unstable
version = "Two"
unstable_features = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
wrap_comments = true
